version: "3"
services:
  crawler:
    build:
      context: .
      dockerfile: DockerFile
    image: figure_crawler
    container_name: crawler
    environment:
      - PYTHONPATH=/workspace/src:/workspace/src/Services/celery
    env_file:
      - .env
    volumes:
      - .:/workspace
      - ./flags:/flags
    working_dir: /workspace
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:13.1
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    container_name: rabbit
    env_file:
      - .env
    ports:
      - 5672:5672
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      - FLASK_URL=crawler:8000
      - NGINX_HOST=figurehook.com
      - NGINX_PORT=80
    ports:
      - 80:80
    volumes:
      - ./nginx/development_templates:/etc/nginx/templates
      - ./flags:/flags
    depends_on:
      - crawler