version: "3"
services:
  crawler:
    build:
      context: .
      dockerfile: DockerFile
    image: figure_crawler
    container_name: crawler
    environment:
      - WORKDIR=/workspace
      - PYTHONPATH=/workspace:/workspace/src/Services/celery
    env_file:
      - .env
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres:13.1
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    container_name: rabbit
    env_file:
      - .env
    ports:
      - 5672:5672
