version: "3"
services:
  crawler:
    build:
      context: .
      dockerfile: DockerFile
    image: figure_crawler
    env_file:
      - .env
    volumes:
      - .:/workspace
      - ./flags:/flags
    working_dir: /workspace
    stdin_open: true
    tty: true
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      backend:
        aliases:
          - rabbit
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
  reverse_proxy:
    build:
      context: Services/reverse_proxy
      dockerfile: DockerFile.dev
    environment:
      - APP_PORT=8000
      - APP_SERVICE=crawler
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./flags:/flags
    depends_on:
      - crawler
    networks:
      - frontend
    secrets:
      - site_cert
      - site_key

networks:
  frontend:
  backend:

secrets:
  site_cert:
    file: ./nginx.crt
  site_key:
    file: ./nginx.key
