version: "3"
services:
  crawler:
    build:
      context: .
    image: figure_crawler
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/workspace
      - ./flags:/flags
    working_dir: /workspace
    stdin_open: true
    tty: true
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      backend:
        aliases:
          - rabbit
  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
networks:
  frontend:
  backend:
