version: "3"
services:
  web:
    image: figure_hook:staging
    container_name: web
    working_dir: /figure_hook
    env_file:
      - deploy.env
    volumes:
      - ./src:/figure_hook/src
      - ./flags:/flags
    entrypoint: ["/bin/sh", ".sh/flask_start.sh"]
    depends_on:
      - celery
  celery:
    image: figure_hook:staging
    working_dir: /figure_hook
    container_name: celery
    env_file:
      - deploy.env
    volumes:
      - ./src:/figure_hook/src
      - ./.sh:/figure_hook/.sh
    entrypoint: ["/bin/sh", ".sh/celery_start.sh"]
    depends_on:
      - scrapy
      - rabbitmq
  scrapy:
    image: figure_hook:staging
    container_name: scrapy
    working_dir: /figure_hook
    ports:
      - 6800:6800
    env_file:
      - deploy.env
    volumes:
      - ./src:/figure_hook/src
      - ./.sh:/figure_hook/.sh
    entrypoint: ["/bin/sh", ".sh/scrapyd_start.sh"]
  rabbitmq:
    image: rabbitmq:3.8.14
    restart: always
    container_name: rabbitmq
    env_file:
      - deploy.env
  redis:
    image: redis:alpine
    restart: always
    container_name: redis_staging
    volumes:
      - ./redis_data:/data
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-staging
    environment:
      - FLASK_URL=web:8000
      - NGINX_PORT=80
    env_file:
      - deploy.env
    ports:
      - 8080:80
    volumes:
      - ./nginx/staging_templates:/etc/nginx/templates
      - ./flags:/flags
    depends_on:
      - web